import { imageUrls, teaProductImages } from './landingAssets'
import type { CategoryLink, PackageProduct, Product } from './landingTypes'

const teaWeight = '25~40克/份'
const soupWeight = '50~120克/包'

export const packages: PackageProduct[] = [
  {
    name: '减脂套餐',
    series: '医学营养系列',
    type: '疗程套餐',
    spec: '1疗程',
    price: '799',
    benefit: '超重 / 腰腹脂肪偏高 / 代谢下降 / 久坐人群',
    packageName: '',
    note: '含四合一营养餐包 + 纤纤茶包 + 21天指导',
    image: imageUrls.slimKit,
    featured: true,
    positioning: '医学营养 + 食养体质调理',
    content: '四合一综合营养膳食餐包 1盒，私人定制纤纤茶包 3盒',
    service: '营养师21天全程跟踪指导',
    audience: '超重人群、腰腹脂肪偏高、代谢下降、久坐办公',
  },
  {
    name: '生发乌发套餐',
    series: '乌发生发系列',
    type: '疗程套餐',
    spec: '1疗程',
    price: '350',
    benefit: '脱发 / 发质干枯 / 熬夜 / 气血不足人群',
    packageName: '',
    note: '含洗发皂 + 黄精芝麻丸 + 九制悦发膏',
    image: imageUrls.hairKit,
    featured: true,
    positioning: '食养调理 + 生活方式指导',
    content: '中药手工洗发皂 1块，黄精芝麻丸 1罐，九制悦发膏 1瓶',
    service: '健康管理师生活方式指导',
    audience: '脱发困扰、发质干枯、熬夜人群、气血不足',
  },
  {
    name: '睡眠套餐',
    series: '膏方/食养粉',
    type: '疗程套餐',
    spec: '1疗程',
    price: '568',
    benefit: '入睡困难 / 易醒多梦 / 睡眠质量差 / 压力大',
    packageName: '',
    note: '含晚安膏 + 酸枣仁粉 + 健管师指导',
    image: imageUrls.sleepKit,
    featured: true,
    positioning: '食养调理 + 健康管理师指导',
    content: '晚安膏 2瓶，酸枣仁百合茯苓桂圆粉 2罐',
    service: '健康管理师生活方式指导',
    audience: '入睡困难、易醒多梦、睡眠质量差、压力较大',
  },
  {
    name: '医学营养干预套餐',
    series: '医学营养系列',
    type: '疗程套餐',
    spec: '1套',
    price: '2388',
    benefit: '体重管理 / 营养干预 / 代谢管理 / 专业跟踪',
    packageName: '',
    note: '含综合营养膳食餐包 4盒及配套工具',
    image: imageUrls.slimKit,
    featured: true,
    positioning: '营养师一对一专业干预',
    content: '综合营养膳食餐包 4盒，赠试纸、腰围尺、多维矿物质',
    service: '营养师一对一专业指导',
    audience: '体重管理、营养干预、代谢管理、专业跟踪',
  },
]

export const coreProducts: Product[] = [
  {
    name: '四合一综合营养膳食餐包',
    series: '医学营养系列',
    type: '单品',
    spec: '盒',
    price: '597',
    benefit: '医学营养干预，全面代餐',
    packageName: '减脂套餐 / 医学营养干预套餐',
    note: '三甲医院同款',
    image: imageUrls.slimKit,
    featured: true,
  },
  {
    name: '私人定制纤纤茶包',
    series: '食养特色茶包系列',
    type: '单品',
    spec: '盒（7袋/份）',
    price: '58',
    benefit: '调节体重，促进代谢',
    packageName: '减脂套餐',
    weight: teaWeight,
    image: teaProductImages['私人定制纤纤饮'],
    featured: true,
  },
  {
    name: '中药手工洗发皂',
    series: '乌发生发系列',
    type: '单品',
    spec: '块',
    price: '68',
    benefit: '中药养护头皮，乌发生发',
    packageName: '生发乌发套餐',
    image: imageUrls.hairProduct,
  },
  {
    name: '黄精芝麻丸',
    series: '乌发生发系列',
    type: '单品',
    spec: '罐',
    price: '128',
    benefit: '补肾益精，乌发润肤',
    packageName: '生发乌发套餐',
    image: imageUrls.hairKit,
  },
  {
    name: '九制悦发膏',
    series: '膏方系列',
    type: '单品',
    spec: '瓶',
    price: '158',
    benefit: '滋养头发，防脱生发',
    packageName: '生发乌发套餐',
    image: imageUrls.tonicPaste,
  },
  {
    name: '晚安膏',
    series: '睡眠调理系列',
    type: '单品',
    spec: '瓶',
    price: '158',
    benefit: '宁心安神，助眠改善',
    packageName: '睡眠套餐',
    image: imageUrls.sleepProduct,
  },
  {
    name: '酸枣仁百合茯苓桂圆粉',
    series: '食养粉系列',
    type: '单品',
    spec: '罐',
    price: '128',
    benefit: '安神宁心，健脾养血',
    packageName: '睡眠套餐',
    image: imageUrls.powderBottle,
  },
  {
    name: '益生菌益生元固体饮料',
    series: '医学营养系列',
    type: '单品',
    spec: '盒（15包×15g）',
    price: '198',
    benefit: '肠道健康，增强免疫',
    packageName: '单独销售',
    note: '至膳益生品牌',
    image: imageUrls.powderPackage,
  },
  {
    name: '营养棒（医学营养套装）',
    series: '医学营养系列',
    type: '单品',
    spec: '8盒套装',
    price: '2180',
    benefit: '全面营养补充，体重管理',
    packageName: '单独销售',
    note: '赠试纸、腰围尺、多维矿物质',
    image: imageUrls.powderDetail,
  },
]

export const teaProducts: Product[] = [
  ['元气是四宝茶', '98', '综合调理，补气养血'],
  ['胖大海润润饮', '68', '润喉利咽，清热解毒'],
  ['苹果四神汤', '68', '健脾养胃，调理消化'],
  ['小吊梨汤', '68', '润肺止咳，生津解渴'],
  ['葛根枳椇子', '68', '解酒护肝，疏通经络'],
  ['黄精黑黑饮', '68', '补肾益精，乌发润肤'],
  ['雪梨玉竹百合茶', '68', '润肺养阴，清心安神'],
  ['苹果黄芪麦冬饮', '68', '益气生津，养阴润燥'],
  ['石斛麦冬白茶饮', '68', '滋阴清热，生津益胃'],
  ['姜枣暖暖茶', '68', '温中散寒，暖胃驱寒'],
  ['五指毛桃茯苓饮', '68', '健脾益气，祛湿化痰'],
  ['金银花牛蒡饮', '68', '清热解毒，疏散风热'],
  ['山楂桑葚玫瑰饮', '68', '消食化积，活血美颜'],
  ['百合茯苓玫瑰饮', '68', '安神宁心，健脾祛湿'],
  ['乌梅甘草桂花饮', '68', '生津止渴，健脾开胃'],
  ['私人定制纤纤饮', '68', '调节体重，促进代谢'],
].map(([name, price, benefit]) => ({
  name,
  series: '食养特色茶包系列',
  type: '茶包',
  spec: '7袋/份',
  price,
  benefit,
  packageName: name === '私人定制纤纤饮' ? '减脂套餐' : '单独销售',
  weight: teaWeight,
  image: teaProductImages[name] ?? imageUrls.tea[name as keyof typeof imageUrls.tea] ?? imageUrls.teaPackage,
}))

export const soupProducts: Product[] = [
  ['山药茯苓薏仁汤', '18', '健脾祛湿，调理脾胃'],
  ['新四神汤', '22', '健脾补肾，祛湿消肿'],
  ['玉竹百合清补汤', '22', '润肺养阴，清心安神'],
  ['五指毛桃茯苓汤', '25', '益气健脾，祛湿消肿'],
  ['人参虫草花菌汤', '25', '补气益肾，增强免疫'],
  ['猴头菇无花果汤', '28', '健胃消食，养护脾胃'],
  ['桑葚百合黄芪汤', '25', '补血养肝，益气安神'],
  ['西洋参麦冬黄芪汤', '32', '益气养阴，生津止渴'],
  ['铁皮石斛麦冬汤', '32', '滋阴清热，养胃生津'],
  ['花胶虫草黄芪汤', '38', '补气养血，滋润养颜'],
].map(([name, price, benefit]) => ({
  name,
  series: '食养药膳系列',
  type: '药膳',
  spec: '独立包装',
  price,
  benefit,
  packageName: '单独销售',
  weight: soupWeight,
  image: imageUrls.soup[name as keyof typeof imageUrls.soup],
}))

export const allProducts = [...packages, ...coreProducts, ...teaProducts, ...soupProducts]
export const featuredProducts = [...packages.slice(0, 3), ...coreProducts.filter((product) => product.featured)]

export const categoryLinks: CategoryLink[] = [
  { id: 'packages', label: '疗程套餐', value: String(packages.length), desc: '350 ~ 2388 元/疗程' },
  { id: 'core-products', label: '核心单品', value: String(coreProducts.length), desc: '58 ~ 2180 元' },
  { id: 'tea-products', label: '食养茶包', value: String(teaProducts.length), desc: '68 ~ 98 元/份' },
  { id: 'soup-products', label: '食养药膳', value: String(soupProducts.length), desc: '18 ~ 38 元/包' },
]

export const navItems = [
  { href: '#packages', label: '套餐' },
  { href: '#core-products', label: '单品' },
  { href: '#tea-products', label: '茶包' },
  { href: '#soup-products', label: '药膳' },
  { href: '#quality', label: '说明' },
  { href: '#wechat', label: '购买' },
]
